name = input("Enter Employee name: ")
age = int(input("Enter your age: "))
contact = int(input("Enter your contact info: "))
email = input("Enter Employee email: ")

print(name)
print(age)
print(contact)
print(email)
print()
print("My name is {0}, age is {1}, contact is {2}, email is {3}".format(name, age, contact, email))
