lst = []
n = int(input("Enter number of Employees: "))
print()
print("Enter Employee details below:")

for i in range(n):
    emp_name = (input("Name:"))
    lst.append(emp_name)
    email = (input("Email:"))
    lst.append(email)
    contact = int(input("Contact:"))
    lst.append(contact)
    adrss = (input("Adress:"))
    lst.append(adrss)
    TA = int(input("TA:"))
    lst.append(TA)
    DA = int(input("DA:"))
    lst.append(DA)
    HRA = int(input("HRA:"))
    lst.append(HRA)
    print(lst)
    print("------------------------------------------------------")
    print()
    lst.clear()